version: 2.1
orbs:
  win: circleci/windows@2.2.0


workflows:
  build_and_package:
    jobs:
      - build-linux:
          context:
            - org-global
      - build-windows:
          context:
            - org-global
jobs:
  build-windows:
    executor: win/default
    steps:
      - checkout
      - run: 
          name: "Install Qt"
          command: |
            cinst --no-progress -y 7zip
            pip install cmake
            pip install aqtinstall
            python -m aqt install 5.14.2 windows desktop win64_msvc2017_64
      - run:
          name: "Update Submodules"
          command: |
            git submodule update --init --recursive --merge .
      - run:
          name: "CMake"
          command: |
            mkdir build
            cd build
            cmake -G "Visual Studio 15 2017" -A x64 -DQt5_DIR=Qt5.14.2\5.14.2\msvc2017_64\lib\cmake\Qt5 ..
            cmake --build . --config Release
            cmake --build . --target bundle --config Release
      - store_artifacts:
          path: /root/project/build

  build-linux:
    docker:
      - image: creatorlars/lzxembedded-base:V0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: "Update Build Environment"
          command: |
            apt-get -q update
            apt-get install -y -q cmake ninja-build make g++ rpm p7zip-full
      - run:
          name: "Install Qt5"
          command: |
            apt-get install -y -q qtbase5-dev qt5-style-plugins
            wget -q -O linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
            install linuxdeployqt /usr/local/bin/
      - run:
          name: "Update Submodules"
          command: |
            git submodule update --init --recursive --merge .
      - run:
          name: "CMake"
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build . --target bundle
      - store_artifacts:
          path: /root/project/build
          


