version: 2.1
workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - org-global

jobs:
  build:
    docker:
      - image: creatorlars/lzxembedded-base:V0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: "Update Build Environment"
          command: |
            apt-get -q update
            apt-get install -y -q cmake ninja-build make g++ rpm p7zip-full
      - run:
          name: "Install Qt5"
          command: |
            apt-get install -y -q qtbase5-dev qt5-style-plugins
            wget -q -O linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
            install linuxdeployqt /usr/local/bin/
      - run:
          name: "Update Submodules"
          command: |
            git submodule update --init --recursive --merge .
      - run:
          name: "CMake"
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build . --target bundle
      - run:
          name: "Run Script"
          command: |
            ls -l
      - store_artifacts:
          path: /root/project/build
          